Feature/8689vv0xm create buttons
jazmindestefano/tpi-frontend-app pull request #13
Opened 2024-09-23 19:37 UTC by candelarfernandez

2024-09-23 19:47 UTC, luccar31 requested changes

2024-09-23 19:47 UTC, luccar31 commented on src/components/Button/CircleButton.tsx
> +          circle: 'w-[80px] h-[80px]',
Creo que sería mejor usar rems como medida. No me parece apropiado poner "circle" como variante del `size`, sería mejor poner algo como "standard". Incluso podría tener varias medidas como "small", "medium" o "large" para adaptarse a los diferentes dispositivos.

2024-09-23 19:47 UTC, luccar31 commented on src/components/Button/CircleButton.tsx
> +          blue: ['text-black bg-[#6D8FE8]']
Dado que el azul sea nuestro color primario, problamente sea mejor idea reemplazar el nombre "blue" por "primary". Luego podriamos tener "secondary" y así.

2024-09-23 19:47 UTC, luccar31 commented on src/components/Button/CustomButton.tsx
Porque hay 2 archivos para un botón? Quizás se podría ver de mergearlos

2024-09-23 19:49 UTC, candelarfernandez commented on src/components/Button/CustomButton.tsx
porque uno es para los que son el circulo que contiene el icono, lo puse aparte por si queremos agregar otros

2024-09-23 19:51 UTC, candelarfernandez commented on src/components/Button/CircleButton.tsx
> +          circle: 'w-[80px] h-[80px]',
okis yo por ahora pondria standard y despues agreamos si necesitamos mas o no?

2024-09-23 19:58 UTC, candelarfernandez commented on src/components/Button/CircleButton.tsx
> +          blue: ['text-black bg-[#6D8FE8]']
mmm esto me genera duda, porque por ejemplo tenes el gris que se usa para cancelar y el naranja que se usa para el paciente en el profesional, si le pones secondary, terciary no se entiende y genera confusion. a mi me parecen mas legibles los otros nombres para identificarlos rapidamente

2024-09-23 19:58 UTC, jazmindestefano commented on src/components/Button/CustomButton.tsx
Cuando decis "ciruclo que contiene un icono" te referis al fondo circular que tiene el icono de volumen por ejemplo? En ese caso podriamos pasarle una prop que sea "isCircle" o algo similar, y ver que el boton de adapte cuando le pasamos esa property en true o false, que piensan?

2024-09-23 19:59 UTC, jazmindestefano commented on src/components/Button/CustomButton.tsx
> +          blue: ['text-black bg-[#6D8FE8]'],
Aca estaria copado que en vez de poner el color duro como #6D8FE8, poder acceder a la tailwind config, donde esta el objeto theme, que tiene el color blue, que como dijo @luccar31 , podriamos ponerle primary :) que piensannnn???

2024-09-23 20:03 UTC, jazmindestefano commented on src/components/Button/CircleButton.tsx
> +          blue: ['text-black bg-[#6D8FE8]']
Entiendo la duda! La diferencia esta entre lo que representa el color en la pagina! los nombres de las variables deberian representar lo mismo, por ejemplo, como nuestro color que va a ser primordial va a ser ese "blue" podriamos ponerle primary, por una cuestion de que si el dia de mañana yo quiero que el color primordial de mi app sea rosa, puedo cambiar el valor y el nombre de la variable no me modifica en nada

Yo trataria de buscar nombres asi para todos los colores, sino nos atamos a un color en particular

2024-09-23 20:03 UTC, candelarfernandez commented on src/components/Button/CustomButton.tsx
sip, exactamente a ese pero que pasa cuando tiene diferentes tamaños/colores? no seria mas facil que tenga un componente x separado?

2024-09-23 20:06 UTC, luccar31 requested changes

2024-09-23 20:06 UTC, luccar31 commented on src/components/Button/CustomButton.tsx
en cuyo caso, si solo se requiere el botón solo con el ícono se lo puede pasar como hijo, por eso está el `{children}`. Sería una cosa así:
```typescript
<CustomButton ...props>
  <Icon ...props>
</CustomButton ...props>
```

2024-09-23 20:06 UTC, luccar31 commented on src/components/Button/CircleButton.tsx
> +          blue: ['text-black bg-[#6D8FE8]']
en realidad no, porque vos tenemos un código de colores seteamos en nuestra app. por eso se usa primary, secondary... o se podria pensar de tenerlo segmentado por paciente, profesional, etc

2024-09-23 20:06 UTC, luccar31 commented on src/components/Button/CustomButton.tsx
> +          blue: ['text-black bg-[#6D8FE8]'],
exactamente. nos tenemos que poner de acuerdo en los colores que vamos a usar en la app y en las convenciones que vamos a usar a lo largo de código

2024-09-23 20:13 UTC, candelarfernandez commented on src/components/Button/CircleButton.tsx
> +          blue: ['text-black bg-[#6D8FE8]']
okis les parece si dejo el blue como primary y los demas con los colores hasta que lo definamos? @luccar31 @jazmindestefano

2024-09-23 20:13 UTC, luccar31 commented on src/components/Button/CircleButton.tsx
> +          blue: ['text-black bg-[#6D8FE8]']
> Entiendo la duda! La diferencia esta entre lo que representa el color en la pagina! los nombres de las variables deberian representar lo mismo, por ejemplo, como nuestro color que va a ser primordial va a ser ese "blue" podriamos ponerle primary, por una cuestion de que si el dia de mañana yo quiero que el color primordial de mi app sea rosa, puedo cambiar el valor y el nombre de la variable no me modifica en nada
> 
> Yo trataria de buscar nombres asi para todos los colores, sino nos atamos a un color en particular

esta es esencia

2024-09-23 21:07 UTC, luccar31 commented on src/components/Button/CircleButton.tsx
> +          circle: 'w-[80px] h-[80px]',
Claro, algo así

2024-09-23 21:09 UTC, luccar31 commented on src/components/Button/CircleButton.tsx
> +          blue: ['text-black bg-[#6D8FE8]']
dale, dejá el blue como primary. fijate en el repo de ejemplo que ahí está el ejemplo claro de como definir colores y temas, y que tailwind se encargue de crear las clases

2024-09-23 21:09 UTC, luccar31 commented on src/components/Button/CircleButton.tsx
> +          blue: ['text-black bg-[#6D8FE8]']
porfa no pongas los colores hardcodeados en los componentes

2024-09-23 21:29 UTC, luccar31 commented on src/components/Button/CircleButton.tsx
> +          blue: ['text-black bg-[#6D8FE8]']
https://tailwindcss.com/docs/theme

2024-09-23 21:36 UTC, candelarfernandez commented on src/components/Button/CircleButton.tsx
> +          blue: ['text-black bg-[#6D8FE8]']
perdon, no se si entendi mal, en tailwind.config puse los colores y esos colores despues los use en los botones, te referis a que no harcodee los colores dentro del config??

2024-09-23 21:39 UTC, candelarfernandez commented on src/components/Button/CircleButton.tsx
> +          blue: ['text-black bg-[#6D8FE8]']
asi queda 
```
 primary: ['text-black bg-blue'],
          secondary: ['text-black bg-grey'],
          terciary: ['text-black bg-orange'],
```

2024-09-24 00:11 UTC, jazmindestefano approved these changes

2024-09-24 00:16 UTC, luccar31 approved these changes

2024-09-24 00:45 UTC, merged